apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-backend
  template:
    metadata:
      labels:
        app: spring-backend
    spec:
      containers:
        - name: spring-backend
          image: ctrlline-backend:latest # 실제 이미지는 overlay에서 patch됨
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: spring-secret
          volumeMounts:
            - name: config-volume
              mountPath: /config/application.yml
              subPath: application.yml
      volumes:
        - name: config-volume
          configMap:
            name: spring-config
