apiVersion: v1
kind: Service
metadata:
  name: ctrlline-api-service
  namespace: dev
spec:
  type: NodePort
  selector:
    app: ctrlline-api
  ports:
  - name: ctrlline-api-port
    port: 30084
    targetPort: 30084
