apiVersion: v1
kind: Service
metadata:
  name: ctrlline-api-service
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: ctrlline-api
  ports:
  - name: ctrlline-api-port
    port: 8088
    targetPort: 8088
